### ISSUE TITLE
Question: Desktop User Agent

### ISSUE THREAD

**Issue by jstart** [itsmeichigo/URLPreview#1]
https://github.com/itsmeichigo/URLPreview/blob/master/Source/NSURL%2BURLPreview.swift#L21
Just curious if there was a specific reason you use a desktop user agent? Do some sites not return the description or image with a standard mobile user agent?

**Comment by itsmeichigo** [comment]
That's true, some sites make it harder to find the elements if we access with mobile user agent so I use desktop agent instead.
