### ISSUE TITLE
Depreciation

### ISSUE THREAD

**Issue by davidseek** [itsmeichigo/URLPreview#3]
`'sendAsynchronousRequest(_:queue:completionHandler:)' was deprecated in iOS 9.0: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h`

Could you please update your code since this is deprecated for a while now? I have tried it my own, but couldn't get it running...

Errors like that slow down the building process in big Xcode projects.

**Comment by itsmeichigo** [comment]
Fixed with last commit.
